use std::fmt::Display;

#[derive(Debug, Clone, Copy)]
pub enum Instruction {
    ADC,
    AND,
    ASL,
    BBR0,
    BBR1,
    BBR2,
    BBR3,
    BBR4,
    BBR5,
    BBR6,
    BBR7,
    BBS0,
    BBS1,
    BBS2,
    BBS3,
    BBS4,
    BBS5,
    BBS6,
    BBS7,
    BCC,
    BCS,
    BEQ,
    BIT,
    BMI,
    BNE,
    BPL,
    BRA,
    BRK,
    BVC,
    BVS,
    CLC,
    CLD,
    CLI,
    CLV,
    CMP,
    CPX,
    CPY,
    DEC,
    DEX,
    DEY,
    EOR,
    INC,
    INX,
    INY,
    JMP,
    JSR,
    LDA,
    LDX,
    LDY,
    LSR,
    NOP,
    ORA,
    PHA,
    PHP,
    PHX,
    PHY,
    PLA,
    PLP,
    PLX,
    PLY,
    RMB0,
    RMB1,
    RMB2,
    RMB3,
    RMB4,
    RMB5,
    RMB6,
    RMB7,
    ROL,
    ROR,
    RTI,
    RTS,
    SBC,
    SEC,
    SED,
    SEI,
    SMB0,
    SMB1,
    SMB2,
    SMB3,
    SMB4,
    SMB5,
    SMB6,
    SMB7,
    STA,
    STP,
    STX,
    STY,
    STZ,
    TAX,
    TAY,
    TRB,
    TSB,
    TSX,
    TXA,
    TXS,
    TYA,
    WAI,
    ILL,
}

#[allow(unused)]
pub trait HasDescription {
    fn desc(&self) -> &str;
}

impl HasDescription for Instruction {
    fn desc(&self) -> &str {
        match self {
            Instruction::ADC => "ADd memory to accumulator with Carry",
            Instruction::AND => "\"AND\" memory with accumulator",
            Instruction::ASL => "Arithmetic Shift one bit Left, memory or accumulator",
            Instruction::BBR0 => "Branch on Bit 0 Reset",
            Instruction::BBR1 => "Branch on Bit 1 Reset",
            Instruction::BBR2 => "Branch on Bit 2 Reset",
            Instruction::BBR3 => "Branch on Bit 3 Reset",
            Instruction::BBR4 => "Branch on Bit 4 Reset",
            Instruction::BBR5 => "Branch on Bit 5 Reset",
            Instruction::BBR6 => "Branch on Bit 6 Reset",
            Instruction::BBR7 => "Branch on Bit 7 Reset",
            Instruction::BBS0 => "Branch of Bit 0 Set",
            Instruction::BBS1 => "Branch of Bit 1 Set",
            Instruction::BBS2 => "Branch of Bit 2 Set",
            Instruction::BBS3 => "Branch of Bit 3 Set",
            Instruction::BBS4 => "Branch of Bit 4 Set",
            Instruction::BBS5 => "Branch of Bit 5 Set",
            Instruction::BBS6 => "Branch of Bit 6 Set",
            Instruction::BBS7 => "Branch of Bit 7 Set",
            Instruction::BCC => "Branch on Carry Clear (Pc=0)",
            Instruction::BCS => "Branch on Carry Set (Pc=1)",
            Instruction::BEQ => "Branch if EQual (Pz=1)",
            Instruction::BIT => "BIt Test",
            Instruction::BMI => "Branch if result MInus (Pn=1)",
            Instruction::BNE => "Branch if Not Equal (Pz=0)",
            Instruction::BPL => "Branch if result PLus (Pn=0)",
            Instruction::BRA => "BRanch Always",
            Instruction::BRK => "BReaK instruction",
            Instruction::BVC => "Branch on oVerflow Clear (Pv=0)",
            Instruction::BVS => "Branch on oVerflow Set (Pv=1)",
            Instruction::CLC => "CLear Cary flag",
            Instruction::CLD => "CLear Decimal mode",
            Instruction::CLI => "CLear Interrupt disable bit",
            Instruction::CLV => "CLear oVerflow flag",
            Instruction::CMP => "CoMPare memory and accumulator",
            Instruction::CPX => "ComPare memory and X register",
            Instruction::CPY => "ComPare memory and Y register",
            Instruction::DEC => "DECrement memory or accumulate by one",
            Instruction::DEX => "DEcrement X by one",
            Instruction::DEY => "DEcrement Y by one",
            Instruction::EOR => "\"Exclusive OR\" memory with accumulate",
            Instruction::INC => "INCrement memory or accumulate by one",
            Instruction::INX => "INcrement X register by one",
            Instruction::INY => "INcrement Y register by one",
            Instruction::JMP => "JuMP to new location",
            Instruction::JSR => "Jump to new location Saving Return (Jump to SubRoutine)",
            Instruction::LDA => "LoaD Accumulator with memory",
            Instruction::LDX => "LoaD the X register with memory",
            Instruction::LDY => "LoaD the Y register with memory",
            Instruction::LSR => "Logical Shift one bit Right memory or",
            Instruction::NOP => "No OPeration",
            Instruction::ORA => "\"OR\" memory with Accumulator",
            Instruction::PHA => "PusH Accumulator on stack",
            Instruction::PHP => "PusH Processor status on stack",
            Instruction::PHX => "PusH X register on stack",
            Instruction::PHY => "PusH Y register on stack",
            Instruction::PLA => "PuLl Accumulator from stack",
            Instruction::PLP => "PuLl Processor status from stack",
            Instruction::PLX => "PuLl X register from stack",
            Instruction::PLY => "PuLl Y register from stack",
            Instruction::RMB0 => "Reset Memory Bit 0",
            Instruction::RMB1 => "Reset Memory Bit 1",
            Instruction::RMB2 => "Reset Memory Bit 2",
            Instruction::RMB3 => "Reset Memory Bit 3",
            Instruction::RMB4 => "Reset Memory Bit 4",
            Instruction::RMB5 => "Reset Memory Bit 5",
            Instruction::RMB6 => "Reset Memory Bit 6",
            Instruction::RMB7 => "Reset Memory Bit 7",
            Instruction::ROL => "ROtate one bit Left memory or accumulator",
            Instruction::ROR => "ROtate one bit Right memory or accumulator",
            Instruction::RTI => "ReTurn from Interrupt",
            Instruction::RTS => "ReTurn from Subroutine",
            Instruction::SBC => "SuBtract memory from accumulator with borrow (Carry bit)",
            Instruction::SEC => "SEt Carry",
            Instruction::SED => "SEt Decimal mode",
            Instruction::SEI => "SEt Interrupt disable status",
            Instruction::SMB0 => "Set Memory Bit 0",
            Instruction::SMB1 => "Set Memory Bit 1",
            Instruction::SMB2 => "Set Memory Bit 2",
            Instruction::SMB3 => "Set Memory Bit 3",
            Instruction::SMB4 => "Set Memory Bit 4",
            Instruction::SMB5 => "Set Memory Bit 5",
            Instruction::SMB6 => "Set Memory Bit 6",
            Instruction::SMB7 => "Set Memory Bit 7",
            Instruction::STA => "STore Accumulator in memory",
            Instruction::STP => "SToP mode",
            Instruction::STX => "STore the X register in memory",
            Instruction::STY => "STore the Y register in memory",
            Instruction::STZ => "STore Zero in memory",
            Instruction::TAX => "Transfer the Accumulator to the X register",
            Instruction::TAY => "Transfer the Accumulator to the Y register",
            Instruction::TRB => "Test and Reset memory Bit",
            Instruction::TSB => "Test and Set memory Bit",
            Instruction::TSX => "Transfer the Stack pointer to the X register",
            Instruction::TXA => "Transfer the X register to the Accumulator",
            Instruction::TXS => "Transfer the X register to the Stack pointer register",
            Instruction::TYA => "Transfer Y register to the Accumulator",
            Instruction::WAI => "WAit for Interrupt",
            Instruction::ILL => "ILLegal opcode",
        }
    }
}

impl Display for Instruction {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let s = match self {
            Instruction::ADC => "ADC",
            Instruction::AND => "AND",
            Instruction::ASL => "ASL",
            Instruction::BBR0 => "BBR0",
            Instruction::BBR1 => "BBR1",
            Instruction::BBR2 => "BBR2",
            Instruction::BBR3 => "BBR3",
            Instruction::BBR4 => "BBR4",
            Instruction::BBR5 => "BBR5",
            Instruction::BBR6 => "BBR6",
            Instruction::BBR7 => "BBR7",
            Instruction::BBS0 => "BBS0",
            Instruction::BBS1 => "BBS1",
            Instruction::BBS2 => "BBS2",
            Instruction::BBS3 => "BBS3",
            Instruction::BBS4 => "BBS4",
            Instruction::BBS5 => "BBS5",
            Instruction::BBS6 => "BBS6",
            Instruction::BBS7 => "BBS7",
            Instruction::BCC => "BCC",
            Instruction::BCS => "BCS",
            Instruction::BEQ => "BEQ",
            Instruction::BIT => "BIT",
            Instruction::BMI => "BMI",
            Instruction::BNE => "BNE",
            Instruction::BPL => "BPL",
            Instruction::BRA => "BRA",
            Instruction::BRK => "BRK",
            Instruction::BVC => "BVC",
            Instruction::BVS => "BVS",
            Instruction::CLC => "CLC",
            Instruction::CLD => "CLD",
            Instruction::CLI => "CLI",
            Instruction::CLV => "CLV",
            Instruction::CMP => "CMP",
            Instruction::CPX => "CPX",
            Instruction::CPY => "CPY",
            Instruction::DEC => "DEC",
            Instruction::DEX => "DEX",
            Instruction::DEY => "DEY",
            Instruction::EOR => "EOR",
            Instruction::INC => "INC",
            Instruction::INX => "INX",
            Instruction::INY => "INY",
            Instruction::JMP => "JMP",
            Instruction::JSR => "JSR",
            Instruction::LDA => "LDA",
            Instruction::LDX => "LDX",
            Instruction::LDY => "LDY",
            Instruction::LSR => "LSR",
            Instruction::NOP => "NOP",
            Instruction::ORA => "ORA",
            Instruction::PHA => "PHA",
            Instruction::PHP => "PHP",
            Instruction::PHX => "PHX",
            Instruction::PHY => "PHY",
            Instruction::PLA => "PLA",
            Instruction::PLP => "PLP",
            Instruction::PLX => "PLX",
            Instruction::PLY => "PLY",
            Instruction::RMB0 => "RMB0",
            Instruction::RMB1 => "RMB1",
            Instruction::RMB2 => "RMB2",
            Instruction::RMB3 => "RMB3",
            Instruction::RMB4 => "RMB4",
            Instruction::RMB5 => "RMB5",
            Instruction::RMB6 => "RMB6",
            Instruction::RMB7 => "RMB7",
            Instruction::ROL => "ROL",
            Instruction::ROR => "ROR",
            Instruction::RTI => "RTI",
            Instruction::RTS => "RTS",
            Instruction::SBC => "SBC",
            Instruction::SEC => "SEC",
            Instruction::SED => "SED",
            Instruction::SEI => "SEI",
            Instruction::SMB0 => "SMB0",
            Instruction::SMB1 => "SMB1",
            Instruction::SMB2 => "SMB2",
            Instruction::SMB3 => "SMB3",
            Instruction::SMB4 => "SMB4",
            Instruction::SMB5 => "SMB5",
            Instruction::SMB6 => "SMB6",
            Instruction::SMB7 => "SMB7",
            Instruction::STA => "STA",
            Instruction::STP => "STP",
            Instruction::STX => "STX",
            Instruction::STY => "STY",
            Instruction::STZ => "STZ",
            Instruction::TAX => "TAX",
            Instruction::TAY => "TAY",
            Instruction::TRB => "TRB",
            Instruction::TSB => "TSB",
            Instruction::TSX => "TSX",
            Instruction::TXA => "TXA",
            Instruction::TXS => "TXS",
            Instruction::TYA => "TYA",
            Instruction::WAI => "WAI",
            Instruction::ILL => "ILL",
        };
        write!(f, "{s}")
    }
}
